package com.picklestech.sch.contgen

/**
 * These lesson titles already exist in the system and are available to be allocated to invented units
 * Created by davidpickles on 21/03/15.
 */
object LsnTitles {

  val titles = Array(
    "Proin sollicitudin",
    "Non Enim Iam Stirpis Bonum Quaeret.",
    "Nam Quid Possumus Facere Melius.",
    "Istam Voluptatem.",
    "Duo Reges: Constructio Interrete.",
    "Quo Studio Aristophanem Putamus Aetatem In Litteris Duxisse",
    "Nam Si Amitti Vita Beata Potest",
    "Hic Quoque Suus Est De Summoque Bono Dissentiens Dici Vere Peripateticus Non Potest",
    "Multoque Hoc Melius Nos Veriusque Quam Stoici",
    "Nunc Haec Primum Fortasse Audientis Servire Debemus",
    "An Est Aliquid Per Se Ipsum Flagitiosum",
    "Quae Autem Natura Suae Primae Institutionis Oblita Est",
    "Sed Quoniam Et Advesperascit Et Mihi Ad Villam Revertendum Est",
    "Odium Autem Et Invidiam Facile Vitabis",
    "Huius Ego Nunc Auctoritatem Sequens Idem Faciam",
    "Honesta Oratio",
    "Maximus Dolor",
    "Duo Reges: Constructio Interrete",
    "Omnes Enim Iucundum Motum",
    "Sed Quid Ages Tandem",
    "Et Harum Quidem Rerum Facilis Est Et Expedita Distinctio",
    "Igitur Neque Stultorum Quisquam Beatus Neque Sapientium Non Beatus",
    "Magna Laus",
    "Quid Censes In Latino Fore",
    "Esse Enim",
    "Eam Tum Adesse",
    "Cenasti In Vita Numquam Bene",
    "Nec Vero Alia Sunt Quaerenda Contra Carneadeam Illam Sententiam",
    "Verba Tu Fingas Et Ea Dicas",
    "Tum Mihi Piso: Quid Ergo",
    "Sed Quid Attinet De Rebus Tam Apertis Plura Requirere",
    "Non Semper",
    "Animum Autem Reliquis Rebus Ita Perfecit",
    "Utrum Igitur Tibi Litteram Videor An Totas Paginas Commovere",
    "Sed Quanta Sit Alias",
    "An",
    "Sed Quia Studebat Laudi Et Dignitati",
    "Quantum Aristoxeni Ingenium Consumptum Videmus In Musicis",
    "Certe",
    "Facile Est Hoc Cernere In Primis Puerorum Aetatulis",
    "Cur Igitur",
    "Cum Autem Negant Ea Quicquam Ad Beatam Vitam Pertinere",
    "Vide",
    "Rhetorice Igitur",
    "Qualis Ista Philosophia Est",
    "Neminem Videbis Ita Laudatum",
    "Ergo Hoc Quidem Apparet",
    "At Ille Pellit",
    "Audio Equidem Philosophi Vocem",
    "Ita Similis Erit Ei Finis Boni",
    "Negat Enim Summo Bono Afferre Incrementum Diem",
    "Non Enim",
    "Quid Sequatur",
    "Consequens Enim Est Et Post Oritur",
    "Quae In Controversiam Veniunt",
    "Quod Autem Satis Est",
    "Plane Idem",
    "Solum Praeterea Formosum",
    "Iam Illud Quale Tandem Est",
    "Cur Tantas Regiones Barbarorum Pedibus Obiit",
    "In Qua Quid Est Boni Praeter Summam Voluptatem",
    "Deinde Dolorem Quem Maximum",
    "Quae Cum Essent Dicta",
    "Quibus Ego Vehementer Assentior",
    "Nam Pyrrho",
    "Nobis Aliter Videtur",
    "Si Quicquam Extra Virtutem Habeatur In Bonis",
    "Sed Haec Omittamus",
    "Num Igitur Eum Postea Censes Anxio Animo Aut Sollicito Fuisse",
    "Mihi Enim Erit Isdem Istis Fortasse Iam Utendum",
    "Sequitur Disserendi Ratio Cognitioque Naturae",
    "Quae Hic Rei Publicae Vulnera Inponebat",
    "Quod Iam A Me Expectare Noli",
    "Quodsi Vultum Tibi",
    "An Eum Discere Ea Mavis",
    "Propter Nos Enim Illam",
    "Aeque Enim Contingit Omnibus Fidibus",
    "Illa Tamen Simplicia",
    "Me Igitur Ipsum Ames Oportet",
    "Nec Mihi Illud Dixeris: Haec Enim Ipsa Mihi Sunt Voluptati",
    "Cum Id Fugiunt",
    "Nam Quid Possumus Facere Melius",
    "Egone Quaeris",
    "Sed Videbimus",
    "Quid Enim Me Prohiberet Epicureum Esse",
    "Neque Solum Ea Communia",
    "Tu Enim Ista Lenius",
    "Quis Suae Urbis Conservatorem Codrum",
    "An Quod Ita Callida Est",
    "Haec Bene Dicuntur",
    "Quem Si Tenueris",
    "Qua Ex Cognitione Facilior Facta Est Investigatio Rerum Occultissimarum",
    "Atque Haec Coniunctio Confusioque Virtutum Tamen A Philosophis Ratione Quadam Distinguitur",
    "Sed Quae Tandem Ista Ratio Est",
    "Quis Pullum Numitorium Fregellanum",
    "Huius",
    "Qui Est In Parvis Malis",
    "Hanc Ergo Intuens Debet Institutum Illud Quasi Signum Absolvere",
    "Quodcumque In Mentem Incideret",
    "Ita Ne Hoc Quidem Modo Paria Peccata Sunt",
    "Quae Quidem Vel Cum Periculo Est Quaerenda Vobis",
    "Bonum Integritas Corporis: Misera Debilitas",
    "Is Ita Vivebat",
    "In Quibus Doctissimi Illi Veteres Inesse Quiddam Caeleste Et Divinum Putaverunt",
    "Quos Quidem Tibi Studiose Et Diligenter Tractandos Magnopere Censeo",
    "Quamquam Id Quidem",
    "Teneo",
    "Si Enim Ad Populum Me Vocas",
    "Hi Curatione Adhibita Levantur In Dies",
    "Et Non Ex Maxima Parte De Tota Iudicabis",
    "Quia Dolori Non Voluptas Contraria Est",
    "Itaque Vides",
    "Quis Enim Redargueret",
    "Iubet Igitur Nos Pythius Apollo Noscere Nosmet Ipsos",
    "Si De Re Disceptari Oportet",
    "Quare Hoc Videndum Est",
    "Ergo Illi Intellegunt Quid Epicurus Dicat",
    "Nam Et Complectitur Verbis",
    "Quid",
    "Nonne Videmus Quanta Perturbatio Rerum Omnium Consequatur",
    "Atque Hoc Loco Similitudines Eas",
    "Dat Enim Intervalla Et Relaxat",
    "Sedulo",
    "Scisse Enim Te Quis Coarguere Possit",
    "Heri",
    "Quamquam Id Quidem Licebit Iis Existimare",
    "Dicet Pro Me Ipsa Virtus Nec Dubitabit Isti Vestro Beato M",
    "Apud Imperitos Tum Illa Dicta Sunt",
    "Dolere Malum Est: In Crucem Qui Agitur",
    "Hoc Est Non Modo Cor Non Habere",
    "Quorum Sine Causa Fieri Nihil Putandum Est",
    "Non Enim Quaero Quid Verum",
    "Non Minor",
    "Gracchum Patrem Non Beatiorem Fuisse Quam Fillum",
    "Si Longus",
    "Praeclare Hoc Quidem",
    "Ergo Id Est Convenienter Naturae Vivere",
    "Sapientem Locupletat Ipsa Natura",
    "Quicquid Porro Animo Cernimus",
    "Nemo Nostrum Istius Generis Asotos Iucunde Putat Vivere",
    "Quamquam Te Quidem Video Minime Esse Deterritum",
    "Quamquam Haec Quidem Praeposita Recte Et Reiecta Dicere Licebit",
    "Refert Tamen",
    "Omnis Enim Est Natura Diligens Sui",
    "Nec Lapathi Suavitatem Acupenseri Galloni Laelius Anteponebat",
    "Tibi Hoc Incredibile",
    "Quis Enim Potest Ea",
    "Vitiosum Est Enim In Dividendo Partem In Genere Numerare",
    "Neutrum Vero",
    "Nummus In Croesi Divitiis Obscuratur",
    "Totum Genus Hoc Zeno Et Qui Ab Eo Sunt Aut Non Potuerunt Aut Noluerunt",
    "Quid Zeno",
    "An Ea",
    "Ut Id Aliis Narrare Gestiant",
    "Illa Sunt Similia: Hebes Acies Est Cuipiam Oculorum",
    "Non Laboro",
    "Nec Vero Sum Nescius Esse Utilitatem In Historia",
    "Minime Vero",
    "Quid Enim Possumus Hoc Agere Divinius",
    "Ut Necesse Sit Omnium Rerum",
    "Ex Quo",
    "Haec Et Tu Ita Posuisti",
    "Invidiosum Nomen Est",
    "Sin Te Auctoritas Commovebat",
    "Quo Plebiscito Decreta A Senatu Est Consuli Quaestio Cn",
    "Equidem",
    "Ut Aliquid Scire Se Gaudeant",
    "Non Autem Hoc: Igitur Ne Illud Quidem",
    "Deinde Prima Illa",
    "Ait Enim Se",
    "Quarum Ambarum Rerum Cum Medicinam Pollicetur",
    "Ille Vero",
    "Sed Quot Homines",
    "Proclivi Currit Oratio",
    "Non Ego Tecum Iam Ita Iocabor",
    "A Primo",
    "Respondent Extrema Primis",
    "Sin Laboramus",
    "Id Sextilius Factum Negabat",
    "Sit Hoc Ultimum Bonorum",
    "Suam Denique Cuique Naturam Esse Ad Vivendum Ducem",
    "Ostendit Pedes Et Pectus",
    "In Qua Si Nihil Est Praeter Rationem",
    "Praeteritis"
  )
}
